<x-layout.app>
    <x-slot name="title">System Settings</x-slot>
    <x-slot name="subtitle">Configure application settings</x-slot>
    <form action="{{ route('settings.update') }}" method="POST" class="max-w-4xl mx-auto space-y-6">@csrf
        <x-ui.card><h3 class="text-lg font-semibold text-slate-800 mb-4">Company Information</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-slate-700 mb-1">Company Name</label><input type="text" name="company_name" value="{{ setting('company_name', 'NexusCRM') }}" class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"></div><div><label class="block text-sm font-medium text-slate-700 mb-1">Email</label><input type="email" name="company_email" value="{{ setting('company_email', '') }}" class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"></div><div class="md:col-span-2"><label class="block text-sm font-medium text-slate-700 mb-1">Address</label><textarea name="company_address" rows="2" class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500">{{ setting('company_address', '') }}</textarea></div><div><label class="block text-sm font-medium text-slate-700 mb-1">Phone</label><input type="text" name="company_phone" value="{{ setting('company_phone', '') }}" class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"></div></div></x-ui-card>
        <x-ui.card><h3 class="text-lg font-semibold text-slate-800 mb-4">Financial Settings</h3><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-slate-700 mb-1">Default Tax Rate (%)</label><input type="number" name="default_tax_rate" value="{{ setting('default_tax_rate', 11) }}" step="0.01" class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"></div><div><label class="block text-sm font-medium text-slate-700 mb-1">Currency Symbol</label><input type="text" name="currency_symbol" value="{{ setting('currency_symbol', 'Rp') }}" class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"></div><div><label class="block text-sm font-medium text-slate-700 mb-1">Payment Terms (days)</label><input type="number" name="payment_terms" value="{{ setting('payment_terms', 14) }}" class="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500"></div></div></x-ui-card>
        <div class="flex justify-end"><button type="submit" class="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">Save Settings</button></div>
    </form>
</x-layout.app>
